# print("Hello world!")
# print("Hello sun!")
# print("Hello sky!")
# print(f"Hello world ,hello sun, hello sky")
# print("Hello world!", end="\n ")
# print("Hello sun!", end=" ")
# print("Hello sky!", end=" \n")
# def test_app_py_exists():
#     assert(path.exists("lib/app.py"))
print("Hello World! Pass this test, please.")
